# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty64"

  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provider "virtualbox" do |vm|
    vm.customize [
      'modifyvm', :id,
      '--memory', '512',
      '--cpus', '2',
      '--name', 'Vagrant Django',
    ]
  end

  config.vm.network :private_network, ip: "192.168.111.222"

  config.vm.synced_folder "../srv", "/srv"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
    ansible.inventory_path = "hosts"
    ansible.limit = 'all'
  end
end
